# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-14 18:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, verbose_name='\u9a8c\u8bc1\u7801')),
                ('email', models.SmallIntegerField(choices=[(0, '\u6fc0\u6d3b'), (1, '\u4fee\u6539\u5bc6\u7801')])),
                ('create_time', models.TimeField(auto_now=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
