# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 15:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userprofiles_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Recipients', models.CharField(max_length=20, verbose_name='\u6536\u4ef6\u4eba')),
                ('telphone', models.CharField(max_length=11, verbose_name='\u8054\u7cfb\u7535\u8bdd')),
                ('city', models.CharField(max_length=20, verbose_name='\u57ce\u5e02')),
                ('address', models.CharField(max_length=50, verbose_name='\u5730\u5740')),
                ('default_add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
