# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20180118_0000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryaddress',
            old_name='Recipients',
            new_name='recipients',
        ),
    ]
