# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-21 08:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20180118_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='delivertaddress',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_delivertaddress', to='account.DeliveryAddress'),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_deliveryaddress', to=settings.AUTH_USER_MODEL),
        ),
    ]
