# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-14 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20180121_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='gender',
            field=models.SmallIntegerField(choices=[(0, '\u7537'), (1, '\u5973')], default=None, null=True, verbose_name='\u6027\u522b'),
        ),
    ]
