# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-05 07:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('buy_num', models.IntegerField(default=0, verbose_name='\u8d2d\u4e70\u6570\u91cf')),
                ('goodinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.GoodsInfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='shopcart',
            unique_together=set([('user', 'goodinfo')]),
        ),
    ]
