# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-05 07:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0007_auto_20180121_1607'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='\u5546\u54c1\u4ef7\u683c')),
                ('goods_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='\u5546\u54c1\u603b\u4ef7')),
                ('count', models.IntegerField(verbose_name='\u8d2d\u4e70\u5546\u54c1\u6570\u91cf')),
                ('goods_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.GoodsInfo', verbose_name='\u5546\u54c1')),
            ],
            options={
                'ordering': ('-id',),
                'verbose_name': '\u8ba2\u5355\u8be6\u60c5',
                'verbose_name_plural': '\u8ba2\u5355\u8be6\u60c5',
            },
        ),
        migrations.CreateModel(
            name='OrderMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=50, unique=True, verbose_name='\u8ba2\u5355\u7f16\u53f7')),
                ('order_time', models.DateTimeField(auto_now_add=True, verbose_name='\u8ba2\u5355\u63d0\u4ea4\u65f6\u95f4')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='\u4ed8\u6b3e\u65f6\u95f4')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='\u603b\u4ef7\u683c')),
                ('is_pay', models.CharField(choices=[('-1', '\u53d6\u6d88'), ('0', '\u521b\u5efa'), ('1', '\u672a\u652f\u4ed8'), ('2', '\u5df2\u652f\u4ed8'), ('3', '\u4ee3\u53d1\u8d27'), ('4', '\u5df2\u53d1\u8d27')], default='0', max_length=5, verbose_name='\u8ba2\u5355\u72b6\u6001')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.DeliveryAddress', verbose_name='\u6536\u8d27\u8be6\u60c5')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u8d2d\u4e70\u7528\u6237')),
            ],
            options={
                'ordering': ('-id',),
                'verbose_name': '\u8ba2\u5355\u4e2d\u5fc3',
                'verbose_name_plural': '\u8ba2\u5355\u4e2d\u5fc3',
            },
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_order.OrderMain', verbose_name='\u8ba2\u5355\u4e2d\u5fc3'),
        ),
    ]
