# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-05 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_order', '0002_auto_20180305_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='goods_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='\u5546\u54c1\u4ef7\u683c'),
        ),
    ]
