# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-11 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_order', '0004_auto_20180310_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='goods_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='\u5546\u54c1\u603b\u4ef7'),
        ),
    ]
